version: "3.5"
services:
  backend:
    build:
      context: .
    env_file:
      - .env
    volumes:
      - ".:/code"
    depends_on:
      - postgres
    ports:
      - "8000:8000"

  postgres:
    image: postgres:11.6-alpine
    volumes:
      - "./pg_data:/var/lib/postgresql/data"
    env_file:
      - .env
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
